### ISSUE TITLE
Move Travel's drop off folder

### ISSUE THREAD

**Issue by keatonwalker** [agrc/perdiem#1]
State travel currently uploads stay data to a folder in my drive.

A folder in team drive should be created instead and Travel will need to be notified of the change.

**Comment by nathankota** [comment]
@brigsz is this something you can do with your drive admin rights - share a folder? The people who need access are:
Karen Maycock
Akemi Dean
Amanda Ronan

**Comment by nathankota** [comment]
"AGRC Will Call" Google Drive has been created, and a "Per Diem" folder has been shared for Fleet and other contributors.

**Comment by steveoh** [comment]
if the sharing is not set up comment and i will reopen this as i got an invite to the storage. 👍
